/*
    Bryan Rainbow
    Dec 7, 2022

    This pipeline does []
*/
pipeline {
    agent any

    parameters {
        booleanParam(defaultValue: false, description: 'Whether to Run the Code', name: 'RUN')
        string(defaultValue: 'Development', description: 'Type of build', name: 'BUILD_TYPE')
    }

    stages {
        stage('Build') {
            steps {
                sh 'echo "Starting Java Build..."'
                sh 'mvn -B -DskipTests clean install'
                sh 'echo "Java Build Complete."'
            }
        }
        stage('Code Quantity') {
            steps {
                sh 'echo "Bryan Rainbow - Group 26"'
                sh 'wc -l < src/main/java/com/mycompany/app/App.java'
            }
        }
        stage('Test') {
            when {
                equals expected: 'Development', actual: params.BUILD_TYPE
            }
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Run') {
            when {
                expression { params.RUN }
            }
            steps {
                sh 'java -jar target/my-app-1.0-SNAPSHOT.jar'
            }
        }
        stage('Build Results') {
            steps {
                sh 'echo "Build ${params.BUILD_TYPE} completed successfully"'
                sh 'echo "I have now completed ACIT 4850!"'
            }
        }
    }
}